appbid/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^seller/', include('seller.urls', namespace='seller')),
    url(r'^usersetting/', include('usersetting.urls', namespace='usersetting')),
    url(r'^query/', include('query.urls', namespace='query')),
    url(r'^bid/', include('bid.urls', namespace='bid')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^transaction/', include('transaction.urls', namespace='transaction')),
    url(r'^social-auth/', include('social_auth.urls')),
    url(r'^auth/', include('auth.urls', namespace='auth')),
    url(r'^help/', include('help.urls', namespace='help')),
    url(r'^developer/', include('developer.urls', namespace='developer')),
    url(r'^joblistings/', include('offer.urls', namespace='offer')),

    url(r'^', include('favicon.urls')),
)

#urlpatterns += (url(r'^admin/django-ses/', include('django_ses.urls')),)
# urlpatterns += patterns('django.contrib.flatpages.views',
#     url(r'^about-us/$', 'flatpage', {'url': '/about-us/'}, name='about'),
#     url(r'^license/$', 'flatpage', {'url': '/license/'}, name='license'),
# )


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth/urls.py
__author__ = 'Jarvis'

from django.conf.urls import patterns, url
from auth import views

urlpatterns = patterns('',
    url(r'^auth-complete/$', views.authComplete, name='auth_complete'),
    url(r'^auth-error/$', views.authError, name='auth_error'),
)

bid/urls.py
__author__ = 'Jarvis'

from django.conf.urls import patterns, url
from bid import views

urlpatterns = patterns('',
    url(r'^bid-create/(?P<pk>\d+)$', views.createBid, name='bid_create'),
    url(r'^bid-list/(?P<pk>\d+)$', views.bidList, name='bid_list'),
)

home/urls.py
__author__ = 'rulongwang'

from django.conf.urls import patterns, url
from home import views
from help import views as helpView


urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^termsandconditions$',helpView.terms,name='terms'),
    url(r'^siterules',helpView.siterules,name='siterule'),
    url(r'^screw-home$', views.screwHome, name='screw_home'),
    url(r'^support',helpView.support,name='support'),
    url(r'^privacy',helpView.privacy,name='privacy'),
    url(r'^contact',helpView.contact,name='contact'),
    url(r'^about',helpView.about,name='about'),
    url(r'^look',views.look,name='look'),
    url(r'^haha',views.haha,name='haha'),

)

query/urls.py
from django.conf.urls import patterns, url
from query import views

urlpatterns = patterns('',
    url(r'^app-detail/(?P<pk>\d*)$', views.getAppDetail, name='app_detail'),
    url(r'^app-detail-comment/(?P<pk>\d*)$', views.addCommentForApp, name='app_detail_comment'),
    url(r'^bid-info/(?P<pk>\d*)$', views.getBidInfo, name='bid_info'),
    url(r'^featured$', views.listFeatured, name='featured'),
    url(r'^list-latest/$', views.listLatest, name='list_latest'),
    url(r'^most-active/$', views.mostActive, name='most_active'),
    url(r'^ending-soon/$', views.endingSoon, name='ending_soon'),
    url(r'^just-sold/$', views.justSold, name='just_sold'),
    url(r'^list-all/$', views.listAll, name='list_all'),
)

query/views.py
import json
import time
import datetime
import string
import urllib

from django.shortcuts import render_to_response, RequestContext, get_object_or_404, HttpResponse, Http404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db.models import Max, Q, Count
from django.contrib.auth.models import User
from django.contrib.comments.models import Comment

from appbid import settings
from appbid import models as appModels
from transaction import models as txnModels
from dashboard import models as dashboardModels
from usersetting import models as userSettingModels
from bid import models as bidModels
from utilities import common
from auth import views as authViews
from notification import views as notificationViews


def listLatest(request):
    """Query the apps info in new listings page."""
    initParam = {}
    page = request.GET.get('page', 1)
    revenue_min = request.GET.get('revenue_min', None)
    category = request.GET.get('category', None)
    subcategory = request.GET.get('subcategory', None)
    monetize = request.GET.get('monetize', None)
    device = request.GET.get('device', None)
    seller = request.GET.get('seller', None)
    currency_id = common.getSystemParam(key='currency', default=2)
    initParam['currency'] = get_object_or_404(appModels.Currency, pk=currency_id)

    if revenue_min is None and category is None and subcategory is None and monetize is None and device is None and seller is None:
        apps = appModels.App.objects.filter(app_type=1, status=2, end_date__gt=datetime.datetime.now()).order_by('-end_date')

    #Revenue Part
    REVENUE_LIST = [2000, 1000, 500, 100, 0]
    initParam['revenue_list'] = []
    for i in range(len(REVENUE_LIST)):
        if i == 0:
            temp_apps = appModels.App.objects.filter(app_type=1, status=2, end_date__gt=datetime.datetime.now(),
                                                     revenue__gte=REVENUE_LIST[i]).order_by('-end_date')
        else:
            temp_apps = appModels.App.objects.filter(app_type=1, status=2, end_date__gt=datetime.datetime.now(),
                                                     revenue__lt=REVENUE_LIST[i-1], revenue__gte=REVENUE_LIST[i]).order_by('-end_date')
        if revenue_min and string.atoi(revenue_min) == REVENUE_LIST[i]:
            apps = temp_apps
            title = _('Revenue(%(param)s/Month)') % {'param': initParam['currency'].currency}
            subTitle = _('Over %(param)s') % {'param': revenue_min}
            initParam['query_tile'] = [title, subTitle, ''.join(['?revenue_min=', revenue_min])]
        initParam['revenue_list'].append([REVENUE_LIST[i], len(temp_apps)])

    #Monetize Part
    initParam['monetize_list'] = []
    if monetize:
        monetizeModel = get_object_or_404(appModels.Monetize, pk=monetize)
    for temp_monetize in appModels.Monetize.objects.all():
        if monetize and monetizeModel == temp_monetize:
            apps = monetizeModel.app_set.filter(app_type=1, status=2, end_date__gt=datetime.datetime.now()).order_by('-end_date')
            initParam['monetize_list'].append([temp_monetize, len(apps)])
            initParam['query_tile'] = [_('Monetize'), temp_monetize.method, ''.join(['?monetize=', monetize])]
        else:
            initParam['monetize_list'].append([temp_monetize, temp_monetize.app_set.filter(app_type=1,
                status=2, end_date__gt=datetime.datetime.now()).count()])

    #Device Part
    initParam['device_list'] = []
    if device:
        deviceModel = get_object_or_404(appModels.Device, pk=device)
    for tem_device in appModels.Device.objects.all():
        if device and deviceModel == tem_device:
            apps = deviceModel.app_set.filter(app_type=1, status=2, end_date__gt=datetime.datetime.now()).order_by('-end_date')
            initParam['device_list'].append([tem_device, len(apps)])
            initParam['query_tile'] = [_('Device'), tem_device.device, ''.join(['?device=', device])]
        else:
            initParam['device_list'].append([tem_device, tem_device.app_set.filter(app_type=1,
                status=2, end_date__gt=datetime.datetime.now()).count()])

    #Category Part
    initParam['category_list'] = []
    if category:
        categoryModel = get_object_or_404(appModels.Category, apple_id=category)
    for temp_category in appModels.Category.objects.all():
        if category and categoryModel == temp_category:
            apps = categoryModel.app_set.filter(app_type=1, status=2, end_date__gt=datetime.datetime.now()).order_by('-end_date')
            initParam['category_list'].append([temp_category, len(apps)])
            initParam['query_tile'] = [_('Category'), temp_category.name, ''.join(['?category=', category])]
        else:
            initParam['category_list'].append([temp_category, temp_category.app_set.filter(app_type=1,
                status=2, end_date__gt=datetime.datetime.now()).count()])
    common.sortWithIndexLie(initParam['category_list'], 1, order='desc')

    #Query data
    initParam['apps'] = queryAppsWithPaginator(request, page=page, apps=apps)

    return render_to_response('query/listing_base.html', initParam, context_instance=RequestContext(request))


def mostActive(request):
    """Query the apps info in most active page."""
    initParam = {}
    page = request.GET.get('page', 1)
    revenue_min = request.GET.get('revenue_min', None)
    category = request.GET.get('category', None)
    subcategory = request.GET.get('subcategory', None)
    monetize = request.GET.get('monetize', None)
    device = request.GET.get('device', None)
    seller = request.GET.get('seller', None)
    currency_id = common.getSystemParam(key='currency', default=2)
    initParam['currency'] = get_object_or_404(appModels.Currency, pk=currency_id)

    app_id = []
    bids = bidModels.Bidding.objects.values('app').annotate(bid_num=Count('app')).order_by('-bid_num')
    for bid in bids:
        app_id.append(bid.get('app'))

    if revenue_min is None and category is None and subcategory is None and monetize is None and device is None and seller is None:
        apps = appModels.App.objects.filter(pk__in=app_id, app_type=1, status=2, end_date__gt=datetime.datetime.now())

    #Revenue Part
    REVENUE_LIST = [2000, 1000, 500, 100, 0]
    initParam['revenue_list'] = []
    for i in range(len(REVENUE_LIST)):
        if i == 0:
            temp_apps = appModels.App.objects.filter(pk__in=app_id, app_type=1, status=2, end_date__gt=datetime.datetime.now(),
                                                     revenue__gte=REVENUE_LIST[i])
        else:
            temp_apps = appModels.App.objects.filter(pk__in=app_id, app_type=1, status=2, end_date__gt=datetime.datetime.now(),
                                                     revenue__lt=REVENUE_LIST[i-1], revenue__gte=REVENUE_LIST[i])
        if revenue_min and string.atoi(revenue_min) == REVENUE_LIST[i]:
            apps = temp_apps
            title = _('Revenue(%(param)s/Month)') % {'param': initParam['currency'].currency}
            subTitle = _('Over %(param)s') % {'param': revenue_min}
            initParam['query_tile'] = [title, subTitle, ''.join(['?revenue_min=', revenue_min])]
        initParam['revenue_list'].append([REVENUE_LIST[i], len(temp_apps)])

    #Monetize Part
    initParam['monetize_list'] = []
    if monetize:
        monetizeModel = get_object_or_404(appModels.Monetize, pk=monetize)
    for temp_monetize in appModels.Monetize.objects.all():
        if monetize and monetizeModel == temp_monetize:
            apps = monetizeModel.app_set.filter(pk__in=app_id, app_type=1, status=2, end_date__gt=datetime.datetime.now())
            initParam['monetize_list'].append([temp_monetize, len(apps)])
            initParam['query_tile'] = [_('Monetize'), temp_monetize.method, ''.join(['?monetize=', monetize])]
        else:
            initParam['monetize_list'].append([temp_monetize, temp_monetize.app_set.filter(
                pk__in=app_id, app_type=1, status=2, end_date__gt=datetime.datetime.now()).count()])

    #Device Part
    initParam['device_list'] = []
    if device:
        deviceModel = get_object_or_404(appModels.Device, pk=device)
    for tem_device in appModels.Device.objects.all():
        if device and deviceModel == tem_device:
            apps = deviceModel.app_set.filter(pk__in=app_id, app_type=1, status=2, end_date__gt=datetime.datetime.now())
            initParam['device_list'].append([tem_device, len(apps)])
            initParam['query_tile'] = [_('Device'), tem_device.device, ''.join(['?device=', device])]
        else:
            initParam['device_list'].append([tem_device, tem_device.app_set.filter(
                pk__in=app_id, app_type=1, status=2, end_date__gt=datetime.datetime.now()).count()])

    #Category Part
    initParam['category_list'] = []
    if category:
        categoryModel = get_object_or_404(appModels.Category, apple_id=category)
    for temp_category in appModels.Category.objects.all():
        if category and categoryModel == temp_category:
            apps = categoryModel.app_set.filter(pk__in=app_id, app_type=1, status=2, end_date__gt=datetime.datetime.now())
            initParam['category_list'].append([temp_category, len(apps)])
            initParam['query_tile'] = [_('Category'), temp_category.name, ''.join(['?category=', category])]
        else:
            initParam['category_list'].append([temp_category, temp_category.app_set.filter(
                pk__in=app_id, app_type=1, status=2, end_date__gt=datetime.datetime.now()).count()])
    common.sortWithIndexLie(initParam['category_list'], 1, order='desc')

    #For sort app by bid numbers
    app_map = {}
    for app in apps:
        app_map[str(app.id)] = app
    new_app = []

templates/query/listing_base.html
{% extends "index.html" %}
{% block mainContent %}
{% load staticfiles %}
        <div id="nav_menu">
        <div id="menu">
        <ul class="sf-menu">
            <li >
                <a href="{% url 'home:home' %}" title="Home">Home</a>
            </li>
            <li >
                <a href="{% url 'query:featured' %}" title="Featured listings">Featured</a>
            </li>
            <li >
                <a href="{% url 'query:list_latest' %}" title="Listings with the latest Apps">New Listings</a>
            </li>
            <li >
                <a href="{% url 'query:most_active' %}" title="Listings with the most bidding activity">Most Active</a>
            </li>
            <li >
                <a href="{% url 'query:ending_soon' %}" title="Listings which are almost over">Ending Soon</a>
            </li>
            <li >
                <a href="{% url 'query:just_sold' %}" title="Listings which have just been sold">Just Sold</a>
            </li>

            <li >
                <a href="{% url 'query:list_all' %}">All</a>
            </li>
            <li class="special">
                <a href="/seller/app-store-link" >Sell Your Apps!</a>
            </li>
        </ul>
        </div>
    </div><!--end of nav-->

        <div class="listing_wrapper">
            <div id="breadcrumb">
                {% if query_tile %}
                <span>{{ query_tile.0 }}-&gt <a href="{{ query_tile.2 }}">{{ query_tile.1 }}</a></span>
                {% else %}
                    <span>&nbsp;</span>
                {% endif %}
            </div>
            <div class="clear"></div>
            <div class="listing_section">
                 <div class="listing_nav">
                    <div class="search_criteria">
                        <h1>Revenue({{ currency.currency }}/Month)</h1>
                        <ul>
                            {% for revenue in revenue_list %}
                                <li><a href="?revenue_min={{ revenue.0 }}"><span class="">Over {{ revenue.0 }}</span><span class="right">{{ revenue.1 }}</span></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="search_criteria">
                        <h1>Monetize </h1>
                        <ul>
                            {% for monetize in monetize_list %}
                                <li><a href="?monetize={{ monetize.0.id }}"><span class="">{{ monetize.0.method }}</span><span class="right">{{ monetize.1 }}</span></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="search_criteria">
                        <h1>Device </h1>
                        <ul>
                            {% for device in device_list %}
                                <li><a href="?device={{ device.0.id }}"><span class="">{{ device.0.device }}</span><span class="right">{{ device.1 }}</span></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="search_criteria">
                        <h1>Category </h1>
                        <ul>
                            {% for category in category_list %}
                                <li class="category_li" {% if forloop.counter > 10 %}style="display: none" {% endif %}>
                                    <a href="?category={{ category.0.apple_id }}"><span class="">{{ category.0.name }}</span><span class="right">{{ category.1 }}</span></a>
                                </li>
                            {% endfor %}
                                <li id='more_show' style="text-align: center">More</li>
                        </ul>
                    </div>
                 </div>
                 <div class="listing_block">
                     <div class="listing_title">
                     </div>
                     <div class="listing_content">
                        <ul >
                            {% for app in apps %}
                            <li>
                                <div class="app_wrapper">
                                       <div class="app_img">
                                           <a href="{% url 'query:app_detail' app.0.id %}{% if query_tile %}?q1={{ query_tile.0 }}&q2={{ query_tile.1 }}&q3={{ query_tile.2 }}{% endif %}">
                                               <img class="img_140x140" src="{{ MEDIA_URL }}{{ app.0.appinfo.icon }}"/>
                                           </a>
                                       </div>

                                       <div class="app_attribute">
                                           <div class="info_detail">
                                            <div>
                                                <h1><a href="{% url 'query:app_detail' app.0.id %}{% if query_tile %}?q1={{ query_tile.0 }}&q2={{ query_tile.1 }}&q3={{ query_tile.2 }}{% endif %}">
                                                    {{ app.0.app_name }}</a></h1>
                                            </div>
                                            <div class="fontcolor_light_grey">
                                               <p>{{ app.0.title }}</p>
                                            </div>
                                            <div class="fontcolor_light_grey">
                                                <span class="att_line">Monthly Downloads: </span>
                                                {{ app.0.dl_amount|default:0 }} time{{ app.0.dl_amount|pluralize }}
                                            </div>
                                            {% if app.0.revenue %}
                                               <div class="fontcolor_light_grey">
                                                   <span class="att_line">Revenue: </span>
                                                   {{ app.0.revenue|floatformat:"-2"|default:0 }} {{ app.0.currency.currency }}
                                               </div>
                                            {% endif %}
                                            {% if app.0.rating %}
                                               <div class="fontcolor_light_grey">
                                                   <span class="att_line">Rating: </span>
                                                   <img src="{% static "images/rating/" %}{{ app.0.rating }}.png"/>
                                               </div>
                                            {% endif %}
                                               <div class="fontcolor_light_grey">
                                                   <span class="att_line">AppleStore Price: </span>
                                                   {{ app.0.appinfo.price|floatformat:"-2"|default:0 }} {{ app.0.currency.currency }}
                                               </div>
                                           </div>

                                           <div class="bidding_info">
                                                <div class="clock_wrapper">

                                                    <div class="clock{{ app.5 }}" title="Closing in: {{ app.4.0|floatformat }} {{ app.4.1 }}{{ app.4.0|floatformat|pluralize }}">

                                                    </div>
                                                </div>
                                               <div style="text-align: center;margin-bottom: 10px;">
                                                   {{ app.1|floatformat:"-2"|default:0 }} {{ app.0.currency.currency }}
                                               </div>
                                               <div class="bid_button" style="margin:0 auto;">
                                                   <a href="{% url 'bid:bid_list' app.0.id %}">
                                                       {{ app.2|floatformat|default:0 }} bid{{ app.2|floatformat|pluralize }}
                                                   </a>
                                               </div>
                                           </div>
                                       </div>
                                </div>
                            </li>
                             {% empty %}
                              <li>No result to find.</li>
                             {% endfor %}
                        </ul>
                     </div>
                     {% if apps %}
                         <div class="pagination" style="float: right">
                            {% if apps.has_previous %}
                                {% if query_tile %}
                                    <a href="{{ query_tile.2 }}&page={{ apps.previous_page_number }}">previous</a>
                                {% else %}
                                    <a href="?page={{ apps.previous_page_number }}">previous</a>
                                {% endif %}
                            {% endif %}
                            {{ apps.number }} of {{ apps.paginator.num_pages }}
                            {% if apps.has_next %}
                                {% if query_tile %}
                                    <a href="{{ query_tile.2 }}&page={{ apps.next_page_number }}">next</a>
                                {% else %}
                                    <a href="?page={{ apps.next_page_number }}">next</a>
                                {% endif %}
                            {% endif %}
                         </div>
                     {% endif %}
                </div>
            </div>
        <div class="clear"></div>

        </div><!--end of listing-wrapper-->
<script type="text/javascript" language="javascript">
    $("#more_show").click(function() {
        $(".category_li").show();
        $("#more_show").hide();
    });
</script>
{% endblock %}

templates/query/listing_detal.html
{% extends "index.html" %}
{% block mainContent %}
{% load staticfiles %}
    <div id="central_block">
      <div class="breadcrumb">

      </div>
      <div class="listing_header">

      </div>

     <div class="hint_block">

     </div>

     <div class="listing_detail">
         <div class="detail_left">

         </div>
         <div class="detail_sidebar">

         </div>
     </div>
    </div>
{% endblock %}