appbid/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^seller/', include('seller.urls', namespace='seller')),
    url(r'^usersetting/', include('usersetting.urls', namespace='usersetting')),
    url(r'^query/', include('query.urls', namespace='query')),
    url(r'^bid/', include('bid.urls', namespace='bid')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^transaction/', include('transaction.urls', namespace='transaction')),
    url(r'^social-auth/', include('social_auth.urls')),
    url(r'^auth/', include('auth.urls', namespace='auth')),
    url(r'^help/', include('help.urls', namespace='help')),
    url(r'^developer/', include('developer.urls', namespace='developer')),
    url(r'^joblistings/', include('offer.urls', namespace='offer')),

    url(r'^', include('favicon.urls')),
)

#urlpatterns += (url(r'^admin/django-ses/', include('django_ses.urls')),)
# urlpatterns += patterns('django.contrib.flatpages.views',
#     url(r'^about-us/$', 'flatpage', {'url': '/about-us/'}, name='about'),
#     url(r'^license/$', 'flatpage', {'url': '/license/'}, name='license'),
# )


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth/urls.py
__author__ = 'Jarvis'

from django.conf.urls import patterns, url
from auth import views

urlpatterns = patterns('',
    url(r'^auth-complete/$', views.authComplete, name='auth_complete'),
    url(r'^auth-error/$', views.authError, name='auth_error'),
)

bid/urls.py
__author__ = 'Jarvis'

from django.conf.urls import patterns, url
from bid import views

urlpatterns = patterns('',
    url(r'^bid-create/(?P<pk>\d+)$', views.createBid, name='bid_create'),
    url(r'^bid-list/(?P<pk>\d+)$', views.bidList, name='bid_list'),
)

query/urls.py
from django.conf.urls import patterns, url
from query import views

urlpatterns = patterns('',
    url(r'^app-detail/(?P<pk>\d*)$', views.getAppDetail, name='app_detail'),
    url(r'^app-detail-comment/(?P<pk>\d*)$', views.addCommentForApp, name='app_detail_comment'),
    url(r'^bid-info/(?P<pk>\d*)$', views.getBidInfo, name='bid_info'),
    url(r'^featured$', views.listFeatured, name='featured'),
    url(r'^list-latest/$', views.listLatest, name='list_latest'),
    url(r'^most-active/$', views.mostActive, name='most_active'),
    url(r'^ending-soon/$', views.endingSoon, name='ending_soon'),
    url(r'^just-sold/$', views.justSold, name='just_sold'),
    url(r'^list-all/$', views.listAll, name='list_all'),
)

seller/urls.py
from django.conf.urls import patterns, url
from seller import views

urlpatterns = patterns('',
    url(r'^app-store-link/(?P<pk>\d*)$', views.registerApp,
        {'flag': 1.1,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:appStore_info',
         'nextPage2': 'seller:verification',
         'saveMethod': views.saveAppStoreLink,
         }, name='appStore_link'),
    url(r'^app-store-info/(?P<pk>\d+)$', views.registerApp,
        {'flag': 1.2,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:marketing',
         'saveMethod': views.saveAppStoreInfo,
         }, name='appStore_info'),
    url(r'^marketing/(?P<pk>\d+)$', views.registerApp,
        {'flag': 2,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:additional_info',
         'saveMethod': views.saveMarketing,
         }, name='marketing'),
    url(r'^additional-info/(?P<pk>\d+)$', views.registerApp,
        {'flag': 3,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:sale',
         'saveMethod': views.saveAdditionalInfo,
         }, name='additional_info'),
    url(r'^sale/(?P<pk>\d+)$', views.registerApp,
        {'flag': 4,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:delivery',
         'saveMethod': views.saveSale,
         }, name='sale'),
    url(r'^delivery/(?P<pk>\d+)$', views.registerApp,
        {'flag': 5,
         'backPage': 'seller/register_content.html',
         'nextPage': '/seller/payment',
         'saveMethod': views.saveDelivery,
         }, name='delivery'),
    #[a-z] for 'new' key word - create the new payment
    url(r'^payment/(?P<pk>\d+)/(?P<sn>[0-9a-z]*)$', views.registerApp,
        {'flag': 6,
         'backPage': 'seller/register_content.html',
         'nextPage': 'order:checkout',
         'saveMethod': views.saveService,
         }, name='payment'),
    url(r'^verification/(?P<pk>\d+)$', views.registerApp,
        {'flag': 7,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:verification',
         'saveMethod': views.saveVerification,
         }, name='verification'),
    url(r'^delete-attachment/(?P<pk>\d*)$', views.deleteAttachment, name='deleteAttachment'),
    url(r'^become-certified-developer$', views.becomeCertifiedDeveloper, name='become_certified_developer'),
)

seller/forms.py
__author__ = 'jarvis'

from django import forms
from appbid import models as appModels


class AppForm(forms.ModelForm):
    app_store_link = forms.URLField(
        widget=forms.TextInput(attrs={'placeholder': 'Eg. https://itunes.apple.com/us/app/YOURAPP/id0000000?mt=8'}),
        required=False,
        help_text="Your app link in app store."

    )
    source_code = forms.BooleanField(
        required=False,
        help_text='Whether you provide the source code and document,when transferring the app.'
    )
    delivery_detail = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'cols': 40, 'rows': 5})
    )
    description = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'cols': 86, 'rows': 25})
    )
    web_site = forms.URLField(
        required=False,
        help_text='The support web site link for your app.'
    )

    class Meta:
        model = appModels.App
        exclude = {'publisher'}

    def __init__(self, *args, **kwargs):
        super(AppForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['apple_id'].widget.attrs['disabled'] = True
            self.fields['app_name'].widget.attrs['disabled'] = True
            self.fields['platform_version'].widget.attrs['disabled'] = True
            self.fields['rating'].widget.attrs['disabled'] = True
            self.fields['category'].widget.attrs['disabled'] = True
            self.fields['device'].widget.attrs['disabled'] = True
            if instance.status == 3:
                self.fields['store_type'].widget.attrs['disabled'] = True
                self.fields['title'].widget.attrs['disabled'] = True
                self.fields['app_store_link'].widget.attrs['disabled'] = True
                self.fields['dl_amount'].widget.attrs['disabled'] = True
                self.fields['revenue'].widget.attrs['disabled'] = True
                self.fields['monetize'].widget.attrs['disabled'] = True
                self.fields['description'].widget.attrs['disabled'] = True
                self.fields['begin_date'].widget.attrs['disabled'] = True
                self.fields['end_date'].widget.attrs['disabled'] = True
                self.fields['source_code'].widget.attrs['disabled'] = True
                self.fields['delivery_detail'].widget.attrs['disabled'] = True
                self.fields['unique_sell'].widget.attrs['disabled'] = True
                self.fields['web_site'].widget.attrs['disabled'] = True
                self.fields['app_type'].widget.attrs['disabled'] = True
            if instance.status == 2 or instance.status == 3:
                self.fields['begin_price'].widget.attrs['disabled'] = True
                self.fields['one_price'].widget.attrs['disabled'] = True
                self.fields['reserve_price'].widget.attrs['disabled'] = True
                self.fields['currency'].widget.attrs['disabled'] = True
                self.fields['minimum_bid'].widget.attrs['disabled'] = True


class AttachmentForm(forms.ModelForm):
    path = forms.FileField(
        label='Select a file'
    )

    class Meta:
        model = appModels.Attachment
        exclude = {'app'}


class AppInfoForm(forms.ModelForm):
    class Meta:
        model = appModels.AppInfo
        exclude = {'app'}

    def __init__(self, *args, **kwargs):
        super(AppInfoForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['price'].widget.attrs['disabled'] = True

templates/seller/register_additional_info.html
{% load staticfiles %}
{% load i18n %}
<script src="{% static "scripts/nicEdit-latest.js" %}"></script>
<script type="text/javascript">
//<![CDATA[
 bkLib.onDomLoaded(function() {
	new nicEditor({fullPanel : true}).panelInstance('appdescription');
    var status = "{{ app_status }}";
    if (status == 3) {
        nicEditors.findEditor("appdescription").disable();
    }
 });
//]]>
</script>

<div id="register_app">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
    <div class="dash_title">{% trans 'App Attributes' %}</div>
    <div id="app_description">
        {% if form.description.errors %}
            <div>
            {{ form.description.errors }}
            </div>
        {% endif %}
        <textarea id="appdescription" name="description" cols="60" rows="20" style="width: 628px; height: 30em;line-height: 1.8em;">
            {{ form.description.value }}
        </textarea>
    </div>

    {% if attachments != None %}
        {% for attachment in attachments %}
        <div style="margin-top: 5px;">
            {{ attachment.name.label_tag }}
            {% if attachment.name.errors %}
                <div style="padding:3px; color: #00b0b0;">
                {{ attachment.name.errors }}
                </div>
            {% endif %}
            <a style="color:#00b0b0; font-weight: bold;" target="_new" href="{{ attachment.path.url }}">{{ attachment.name }}</a>
            {% if app_status != 3 %}
<!--        TODO: It is better to use the image with delete meaning. -->
            <input id="{{ attachment.id }}" name="{{ attachment.name }}" type="button" class="remove" value="Remove" onclick="deleteAttachment(this)">
            {% endif %}
        </div>
        {% endfor %}
    {% endif %}
    {% if app_status != 3 %}
    <div id="attachment">
         <div>
            <label for="attachment">{% trans 'Add attachment' %}</label> <span style="font-size: 12px;">{% blocktrans %}(Only accepts  <b>txt/pdf/image</b> type. Max size < {{ attachmentSize }}M.){% endblocktrans %}</span>
        </div>
        {{ attachmentError }}
        {% if attachmentForm %}
            <div style="margin-top: 20px;">

                {% if attachmentForm.path.errors %}
                    <div style="margin-top: 5px;padding:3px;">
                    {{ attachmentForm.path.errors }}
                    </div>
                {% endif %}
                {{ attachmentForm.path.label_tag }}
                {{ attachmentForm.path }}
                <input id="add" type="button" value="{% trans 'Add' %}" >
            </div>
        {% endif %}
    </div>
    {% endif %}
        <input id="next" class="nextbutton" type="submit" name="next" value="{% trans 'Next' %}"/>
    </form>

<script type="text/javascript" language="javascript">
    function deleteAttachment(obj) {
        id = $(obj).attr("id");
        name = $(obj).attr("name");
        $.ajax({
            type:"POST",
            url:"{% url 'seller:deleteAttachment' id %}",
            data:{
                id:id,
                name:name,
                csrfmiddlewaretoken: "{{ csrf_token }}"
            },
            success:function(data) {
                if(data.ok === 'true')
                    $(obj).parent().remove();
                else
                    alert(data.message);
            },
            error:function(){
                alert("Delete failed, please try again.");
            }
        });
    }

    $("#add").click(function() {
        $("#attachment").append(
            '<div>'+
                '{{ attachmentForm.path.label_tag }} '+
                '{% if attachmentForm.path.errors %}'+
                    '<div>'+
                    '{{ attachmentForm.path.errors }}'+
                    '</div>'+
                '{% endif %}'+
                '{{ attachmentForm.path }} '+
                '<input type="button" value="Remove"  class="remove" onclick="removeNode(this)">'+
            '</div>');
    });

    function removeNode(obj) {
        $(obj).parent().remove();
    }
</script>
</div>

templates/seller/register_app.html
<div id="register_app">
    <form action="" method="post">
        {% csrf_token %}

        {{ form.title.label_tag }}
        {% if form.title.errors %}
            <div>
            {{ form.title.errors }}
            </div>
        {% endif %}
        {{ form.title }}

        {{ form.description.label_tag }}
        {% if form.description.errors %}
            <div>
            {{ form.description.errors }}
            </div>
        {% endif %}
        {{ form.description }}

        <input type="submit" name="next" value="next"/>
    </form>

</div>

templates/seller/register_appStore_info.html
<div id="register_app" xmlns="http://www.w3.org/1999/html">
{% load i18n %}
    <div class="errors_block">
    </div>
 <form action="" method="post">
        {% csrf_token %}
      <div class="dash_title">{% trans 'Additional Information' %}</div>
        <div class="register_icon">
            <span style="font-weight: bold;">{% trans 'App Icon' %}</span>
            {% if appInfoForm.icon.errors %}
                <div class="return_error">
                {{ appInfoForm.icon.errors }}
                </div>
            {% endif %}
            {% if appInfoForm.icon.value %}
            <div class="icon_wrapper">
            <img width="57px" height="57px" src="{{ MEDIA_URL }}{{ appInfoForm.icon.value }}"/>
            </div>
            {% endif %}
        </div>

        <div class="field_block">
            <span style="font-weight: bold;">{% trans 'App name' %}</span>
            {% if form.app_name.errors %}
                <div class="return_error">
                {{ form.app_name.errors }}
                </div>
            {% endif %}
            {{ form.app_name }}
        </div>

        <div class="field_block">
            <span style="font-weight: bold;">{% trans 'Apple id' %}</span>
            {% if form.apple_id.errors %}
                <div class="return_error">
                {{ form.apple_id.errors }}
                </div>
            {% endif %}
            {{ form.apple_id }}
        </div>

        <div class="field_block">
            <span style="font-weight: bold;">{% trans 'Platform version' %}</span>
            {% if form.platform_version.errors %}
                <div class="return_error">
                {{ form.platform_version.errors }}
                </div>
            {% endif %}
            {{ form.platform_version }}
        </div>

        <div class="field_block">
            <span style="font-weight: bold;">{% trans 'Rating' %}</span>
            {% if form.rating.errors %}
                <div class="return_error">
                {{ form.rating.errors }}
                </div>
            {% endif %}
            {{ form.rating }}
        </div>

        <div class="field_block_selected">
            <span style="font-weight: bold;">{% trans 'Category' %}</span>
            {% if form.category.errors %}
                <div class="return_error">
                {{ form.category.errors }}
                </div>
            {% endif %}
            {{ form.category }}
        </div>

        <div class="field_block_selected">
            <span style="font-weight: bold;">{% trans 'Device' %}</span>
            {% if form.device.errors %}
                <div class="return_error">
                {{ form.device.errors }}
                </div>
            {% endif %}
            {{ form.device }}
        </div>

        <div class="field_block">
            <span style="font-weight: bold;">{% trans 'Price' %}</span>
            {% if appInfoForm.price.errors %}
                <div>
                {{ appInfoForm.price.errors }}
                </div>
            {% endif %}
            {{ appInfoForm.price }}
        </div>


    {{ appContent }}
        <div class="clear"></div>
        <div class="button_block">
            <input id="next" class="nextbutton" type="submit" name="next" value="{% trans 'Next' %}"/>
        </div>
   </form>

</div>

templates/seller/register_appStore_link.html
{% load staticfiles %}
{% load i18n %}
<div id="register_app">
   <div class="errors_block">
            {% if form.title.errors %}
                {{ form.title.errors }}
            {% endif %}
            {% if form.app_store_link.errors %}
                {{ form.app_store_link.errors }}
            {% endif %}
            {% if error_msg %}
                    {{ error_msg }}
            {% endif %}
   </div>
      <div>
          <span style="float: right;margin-top: -30px;font-weight: bold;color: #00b0b0;">
              {% if developer_status == None or developer_status == 1 %}
                  <input id="id_developer" type="checkbox" />
                  {% trans 'Become' %}<a href="#">{% trans 'Certified Developer' %}</a>
              {% elif developer_status != None and developer_status == 2 %}
                  <input id="id_developer" type="checkbox" checked disabled />
                  {% trans 'Pending' %}<a href="#">{% trans 'Certified Developer' %}</a>
              {% elif developer_status != None and developer_status == 3 %}
                  <input id="id_developer" type="checkbox" checked />
                  {% trans 'Is' %}<a href="#">{% trans 'Certified Developer' %}</a>
              {% elif developer_status != None and developer_status == 4 %}
                  <input id="id_developer" type="checkbox" />
                  {% trans 'Apply' %}<a href="#">{% trans 'Certified Developer' %}</a>{% trans 'Failed' %}
              {% endif %}
          </span>
      </div>

      <div class="dash_title">{% trans 'Appstore Info' %}</div>
        <form action="" method="post">
            {% csrf_token %}
      <div class="field_block_addi">
        <div class="left" style="width:120px;margin-top:15px;">
            <div style="width:100px:height:30px;font-weight: bold;">*{% trans 'App Title' %}</div>
        </div>
        <div class="right" style="width:420px;">
             {{ form.title }}
        </div>
      </div>

      <div class="field_block_addi">
        <div class="left" style="width:120px;margin-top:15px;">
            <div style="width:100px:height:30px;font-weight: bold;">*{% trans 'App store link' %}</div>
        </div>
       <div id="progressor">
              <img src="{% static "images/loading.gif" %}" style="width:30px;height: 30px;"/>
        </div>
        <div class="right" style="width:420px;">
             {{ form.app_store_link }}
        </div>
      </div>

      <div class="field_block_addi">
        <div class="left" style="width:120px;margin-top:15px;">
            <div style="width:100px:height:30px;font-weight: bold;">*{% trans 'App Type' %}</div>
        </div>
        <div class="right" style="width:420px;">
             <span style="padding-left: 10px;">{{ form.app_type }}</span>
        </div>
      </div>
    <div style="padding:20px 0 0 30px; font-size: 12px;color: #00b0b0;;">
        * {% trans 'indicate the filed is mandatory.' %} </br>
        {% trans 'Please be notice that we only support iOS/OSX apps.' %} </br>
    </div>

        <div class="button_block">
            <input id="next" class="nextbutton" type="submit" name="next" value="{% trans 'Next' %}"/>
        </div>
        </form>


        <div class="step_block" style="clear:both;" >
            {% if apps %}
            <div style="color:#00b0b0;font-weight: bold;">{% trans 'Your draft apps:' %}</div>
                <ul class="existing_apps">
                {% for app in apps %}
                <li>
                <div class="app_list_name " style="clear:both;">
                    <a  href="{% url 'seller:appStore_link' app.id %}">{{ app.title }}</a>
                </div>
                <div class="app_list_attr">
                    {% trans 'Last modified:' %}{{ app.last_modify|date:"Y-m-d H:i" }}
                </div>
                </li>
                {% endfor %}
                </ul>
            {% endif %}
        </div>
<script type="text/javascript" language="javascript">
    $("#id_developer").click(function() {
        if ($("#id_developer").is(':checked')) {
            $.ajax({
                type:"POST",
                url:"{% url 'seller:become_certified_developer' %}",
                data:{
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                success:function(data) {
                    if(data.ok === 'true') {
                        alert(data.message);
                    }
                    else {
                        alert(data.message);
                    }
                }
            });
        }
    });
    $("#next").click(function() {
        if ($("#id_title").val().trim() == "") {
            $(".errors_block").html("Title is required.");
            return false;
        }
        if ($("#id_app_store_link").val().trim() == "") {
            $(".errors_block").html("App store link is required.");
            return false;
        }
        if ($("#id_app_type").val().trim() == "") {
            $(".errors_block").html("App type is required.");
            return false;
        }
        $("#progressor").show("fast");
    });
</script>
<div class="clear"></div>
</div>

templates/seller/register_content.html
{% extends "index.html" %}
{% block mainContent %}
{% load staticfiles %}
<div class="register_block">
{% include "seller/register_nav.html" %}

    {% ifequal flag 1.1 %}
    {% include "seller/register_appStore_link.html" %}
    {% endifequal %}

    {% ifequal flag 1.2 %}
    {% include "seller/register_appStore_info.html" %}
    {% endifequal %}

    {% ifequal flag 2 %}
    {% include "seller/register_marketing.html" %}
    {% endifequal %}

    {% ifequal flag 3 %}
    {% include "seller/register_additional_info.html" %}
    {% endifequal %}

     {% ifequal flag 4 %}
    {% include "seller/register_sale.html" %}
    {% endifequal %}

    {% ifequal flag 5 %}
    {% include "seller/register_delivery.html" %}
    {% endifequal %}

    {% ifequal flag 6 %}
    {% include "seller/register_payment.html" %}
    {% endifequal %}

    {% ifequal flag 7 %}
    {% include "seller/register_verification.html" %}
    {% endifequal %}
<div class="clear"></div>
</div>
{% endblock %}

templates/seller/register_delivery.html
<div id="register_app">

    <div class="errors_block">
            {% if form.unique_sell.errors %}
            <div>
            {{ form.unique_sell.errors }}
            </div>
            {% endif %}
            {% if form.source_code.errors %}
            <div>
            {{ form.source_code.errors }}
            </div>
            {% endif %}
            {% if form.delivery_detail.errors %}
            <div>
            {{ form.delivery_detail.errors }}
            </div>
            {% endif %}
            {% if form.web_site.errors %}
            <div>
            {{ form.web_site.errors }}
            </div>
            {% endif %}

   </div>


    <form action="" method="post">
        {% csrf_token %}
      <div class="dash_title">Your claimed delivery</div>
        <div class="field_block_deliery">
            <div class="left" style="width:300px;">
                <div style="width:300px:height:20px;">{{ form.unique_sell.label_tag }}</div>
                <div class="help_text">Please specify if this app will be sold only once.</div>
            </div>
            <div class="right" style="width:50px">
                 {{ form.unique_sell }}
            </div>
        </div>
        <div class="clear"></div>
        <div class="field_block_deliery">
            <div class="left" style="width:300px;">
                <div style="width:300px:height:20px;">{{ form.source_code.label_tag }}</div>
                <div class="help_text">{{ form.source_code.help_text }}</div>
            </div>
            <div class="right" style="width:50px">
                 {{ form.source_code }}
            </div>
        </div>
        <div class="clear"></div>
        <div class="field_block_deliery" style="height:50px;">
            <div class="left" style="width:200px;">
                <div style="width:300px:height:20px;">{{ form.delivery_detail.label_tag }}</div>
                <div class="help_text">Please list the deliverable items of this APP .</div>
            </div>
            <div class="right">
                {{ form.delivery_detail }}
            </div>
        </div>
        <div class="clear"></div>
        <div class="field_block_deliery">
            <div class="left" style="width:300px;">
                <div style="width:300px:height:30px;">{{ form.web_site.label_tag }}</div>
                <div class="help_text"> {{ form.web_site.help_text }}</div>
            </div>
            <div class="right" style="width:50px">
                 {{ form.web_site }}
            </div>
        </div>
            <div class="button_block">
                <input id="next" class="nextbutton" type="submit" name="next" value="Next"/>
            </div>
    </form>

</div>

templates/seller/register_nav.html
{% load i18n %}
<div id="register_nav">
    <div class="nav_title">{% trans 'Basic Info For Your Listing' %}</div>
    <ul id="register_new_nav">
        <li class="{{ app_store_link }}point_icon">
            <a href="{% url 'seller:appStore_link' app_id %}">{% trans 'AppleStore Info' %}</a>
        </li>
        {% if app_id %}
        {% if app_type == None or app_type != 1 %}
        <li class="{{ app_store_info }}point_icon">
            <a href="{% url 'seller:appStore_info' app_id %}">{% trans 'App Attributes' %}</a>
        </li>
        <li class="{{ marketing }}point_icon">
            <a href="{% url 'seller:marketing' app_id %}">{% trans 'Revenue/Monetization' %}</a>
        </li>
        <li class="{{ additional_info }}point_icon">
            <a href="{% url 'seller:additional_info' app_id %}">{% trans 'Additional Info' %}</a>
        </li>
        <li class="{{ sale }}point_icon">
            <a href="{% url 'seller:sale' app_id %}">{% trans 'Price Setting' %}</a>
        </li>
        <li class="{{ delivery }}point_icon">
            <a href="{% url 'seller:delivery' app_id %}">{% trans 'Your Delivery' %}</a>
        </li>
        <li class="{{ payment }}point_icon">
            <a href="{% url 'seller:payment' app_id serviceDetail.sn %}">{% trans 'Payment' %}</a>
        </li>
        {% endif %}
        <li class="{{ verification }}point_icon">
            <a href="{% url 'seller:verification' app_id %}">{% trans 'App Verification' %}</a>
        </li>
        {% endif %}
    </ul>
    {% if app_id %}
    <div class="preview_buttons"><a href="{% url 'query:app_detail' app_id %}" style="color:#00b0b0;">{% trans 'Preview your App' %}</a></div>
    {% endif %}
</div>

templates/seller/register_payment.html
<div id="register_app">
<div style="color: red;">
    {{ payment_msg }}
</div>
    <div class="dash_title">Choose service</div>
    <form action="" method="post">
    {% csrf_token %}
    {% for serviceItem in serviceItems %}
        <div class="field_block_payment">

            <div class="left" style="width:300px;">
            <div style="width:300px:height:20px; font-weight: bold;"> {{ serviceItem.short_text }}</div>
            <div style="width:300px:height:40px; font-size: 12px;">{{ serviceItem.long_text }}</div>
             </div>
             <div class="right" style="width:60px">
             {{ serviceItem.price }}$
                 <input type="checkbox" name="serviceItem_id" value="{{ serviceItem.id }}"
                       price="{{ serviceItem.price }}" onclick="checkServiceItem(this)"
                       {% ifequal serviceItem.is_basic_service True %}checked="checked" disabled
                       {% else %}
                       {% if serviceItem in selectItems %}checked="checked"{% endif %}
                       {% if serviceDetail and serviceDetail.is_payed == True %} disabled {% endif %}
                       {% endifequal %}>
                {% ifequal serviceItem.is_basic_service True %}
                <input type="hidden" name="serviceItem_id" value="{{ serviceItem.id }}">
                {% endifequal %}
             </div>
        </div>
         <div class="clear"></div>
    {% endfor %}
    <div class="field_block_payment">
        <div class="right" style="width:120px;text-align: right">
        <label>Total:</label>
        <label id="total">{{ amount|default:0 }}</label><b>$</b>
        </div>
        <div class="right" style="width:500px;text-align: right;">
        <label>Discount Rate:</label>
        <label id="total">{{ discount_rate }}</label><b></b>
        </div>


        <div class="right" style="width:500px;text-align: right;">
        <label>Actual Total:</label>
        <label id="actual_total"></label><b>$</b>
        </div>
    </div>
    <div class="right" style="width:250px;">
    {% if serviceDetail == None or serviceDetail and serviceDetail.is_payed != True %}
        <input id="next" class="nextbutton" type="submit" name="next" value="Checkout"/>
    {% else %}
        <a href="{% url 'seller:payment' app_id 'new' %}"><input id="new_payment" class="nextbutton" type="button" value="New Payment"></a>
    {% endif %}
    </div>
    </form>

<script type="text/javascript" language="javascript">
    var total =  parseFloat(($("#total").text()).replace(",", "."));
    var discount_rate = parseFloat("{{ discount_rate }}");
    $("#actual_total").html(total*discount_rate);
    function checkServiceItem(obj) {
        var price = $(obj).attr("price");
        if ($(obj).is(':checked') == true) {
            total += parseFloat(price.replace(",", "."));
        }
        else {
            total -= parseFloat(price.replace(",", "."));
        }
        $("#total").html(total);
        $("#actual_total").html(total*discount_rate);
        $("#discount_rate").html(1000*discount_rate)
    }
</script>
</div>