appbid/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^seller/', include('seller.urls', namespace='seller')),
    url(r'^usersetting/', include('usersetting.urls', namespace='usersetting')),
    url(r'^query/', include('query.urls', namespace='query')),
    url(r'^bid/', include('bid.urls', namespace='bid')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^transaction/', include('transaction.urls', namespace='transaction')),
    url(r'^social-auth/', include('social_auth.urls')),
    url(r'^auth/', include('auth.urls', namespace='auth')),
    url(r'^help/', include('help.urls', namespace='help')),
    url(r'^developer/', include('developer.urls', namespace='developer')),
    url(r'^joblistings/', include('offer.urls', namespace='offer')),

    url(r'^', include('favicon.urls')),
)

#urlpatterns += (url(r'^admin/django-ses/', include('django_ses.urls')),)
# urlpatterns += patterns('django.contrib.flatpages.views',
#     url(r'^about-us/$', 'flatpage', {'url': '/about-us/'}, name='about'),
#     url(r'^license/$', 'flatpage', {'url': '/license/'}, name='license'),
# )


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth/urls.py
__author__ = 'Jarvis'

from django.conf.urls import patterns, url
from auth import views

urlpatterns = patterns('',
    url(r'^auth-complete/$', views.authComplete, name='auth_complete'),
    url(r'^auth-error/$', views.authError, name='auth_error'),
)

bid/urls.py
__author__ = 'Jarvis'

from django.conf.urls import patterns, url
from bid import views

urlpatterns = patterns('',
    url(r'^bid-create/(?P<pk>\d+)$', views.createBid, name='bid_create'),
    url(r'^bid-list/(?P<pk>\d+)$', views.bidList, name='bid_list'),
)

usersetting/urls.py
__author__ = 'rulongwang'

from django.conf.urls import patterns, url
from usersetting import views


urlpatterns = patterns('',
    url(r'^login/$', views.loginView, name='login_view'),
    url(r'^logout/$', views.logoutView, name='logout_view'),
    url(r'^forget-password/$', views.forgetPassword, name='forget_password'),
    url(r'^reset-password/(?P<type>\d{1})/(?P<user_id>\d+)/(?P<username>\S+)/(?P<token>\w{30})$', views.resetPassword,
        name='reset_password'),

    url(r'^register/$', views.register, name='register_view'),
    url(r'^username-verified/(?P<username>\S*)$', views.ajaxUserVerified, name='username_verified'),
    url(r'^email-verified/(?P<email>\w*)$', views.ajaxUserVerified, name='email_verified'),
    url(r'^register-active/(?P<username>\S+)/(?P<pk>\d+)$', views.registerActive, name='register_active'),
    #https://github.com/users/jarvisjia/emails/5800727/confirm_verification/2cd4ea255dd3e1deae130868d75cfa28fc423034
    url(r'^(?P<username>\S+)/emails/(?P<pk>\d+)/register-confirm-verification/(?P<confirm_token>\w{30})$',
        views.registerActiveConfirm, name='register_active_confirm'),
    url(r'^home/$', views.authHome, name='home'),

    url(r'^security-verification-password$', views.securityVerification,
        {'current': 'usersetting:change_password',
         'saveMethod': views.changePassword,
        }, name='security_verification_password'),
    url(r'^security-verification-email$', views.securityVerification,
        {'current': 'usersetting:security_setting_email',
         'saveMethod': views.securitySettingEmail,
        }, name='security_verification_email'),
    url(r'^security-verification-phone$', views.securityVerification,
        {'current': 'usersetting:security_setting_phone',
         'saveMethod': views.securitySettingPhone,
        }, name='security_verification_phone'),
    url(r'^security-verification-payment$', views.securityVerification,
        {'current': 'usersetting:payment_setting',
         'saveMethod': views.paymentAccount,
        }, name='security_verification_payment'),
    url(r'^send-pin$', views.sendPIN, name='send_PIN'),

    url(r'^user-detail$', views.userDetail, name='user_detail'),
    url(r'^public-profile$', views.userPublicProfile, name='public_profile'),
    url(r'^subscription-setting$', views.subscriptionSetting, name='subscription_setting'),
    url(r'^change-password$', views.changePassword, name='change_password'),
    url(r'^security-setting$', views.securitySetting, name='security_setting'),

    url(r'^security-setting-email$', views.securitySettingEmail, name='security_setting_email'),
    url(r'^security-setting-email-update$', views.securitySettingEmailUpdate, name='security_setting_email_update'),
    url(r'^(?P<username>\S+)/emails/(?P<pk>\d+)/email-security-verification/(?P<confirm_token>\w+)$',
        views.securitySettingEmailConfirm, name='security_setting_email_confirm'),
    url(r'^security-setting-phone$', views.securitySettingPhone, name='security_setting_phone'),

    url(r'^social-setting$', views.socialConnection, name='social_setting'),
    url(r'^payment-setting/(?P<next>\S*)$', views.paymentAccount, name='payment_setting'),
)

usersetting/models.py
__author__ = 'rulongwang'

from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin


class UserPrivateItem(models.Model):
    """UserPrivateItem table info - such as is_bid_approved."""
    key = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)


class UserPrivateItemAdmin(admin.ModelAdmin):
    """The set of UserPrivateItem table displaying in admin page."""
    list_display = ('key', 'description')


class UserPrivateSetting(models.Model):
    """UserPrivateSetting table info."""
    user = models.ForeignKey(User)
    user_private_item = models.ForeignKey(UserPrivateItem)
    value = models.TextField()


class UserDetail(models.Model):
    """UserDetail table info."""
    DEVELOPER_STATUS = (
        (1, "Normal User"),
        (2, "Pending"),
        (3, "Certified Developer"),
        (4, "Failed"),
    )
    user = models.OneToOneField(User, blank=True)
    developer_status = models.IntegerField(choices=DEVELOPER_STATUS, null=True, blank=True, default=1)
    birthday = models.DateField(blank=True, null=True)
    real_name = models.CharField(blank=True, max_length=255, null=True)
    street_address = models.CharField(blank=True, max_length=300, null=True)
    city = models.CharField(blank=True, max_length=255, null=True)
    state_provience = models.CharField(blank=True, max_length=255, null=True)
    post_code = models.CharField(blank=True, max_length=255, null=True)
    country = models.CharField(blank=True, max_length=255, null=True)


class UserDetailAdmin(admin.ModelAdmin):
    """The set of UserDetail table displaying in admin page."""
    list_display = ('user', 'real_name', 'city', 'country')


def content_file_name(instance, filename):
    """The path of saving attachment file. The pattern is user_id/filename"""
    return '/'.join([str(instance.user.id), 'avatar.jpg'])


class UserPublicProfile(models.Model):
    """UserPublicProfile table info."""
    GENDER_TYPES = (
        (1, 'Male'),
        (2, 'Female'),
        (3, 'Secret'),
    )
    user = models.OneToOneField(User, blank=True)
    thumbnail = models.FileField(max_length=255, upload_to=content_file_name, null=True, blank=True)
    gender = models.IntegerField(choices=GENDER_TYPES, blank=True, default=3, null=True)
    homepage = models.CharField(max_length=255, blank=True, null=True)
    twitter_account = models.CharField(max_length=255, blank=True, null=True)
    facebook_account = models.CharField(max_length=255, blank=True, null=True)
    weibo_account = models.CharField(max_length=255, blank=True, null=True)
    weixin_account = models.CharField(max_length=255, blank=True, null=True)


class UserPublicProfileAdmin(admin.ModelAdmin):
    """The set of UserPublicProfile table displaying in admin page."""
    list_display = ('user', 'gender', 'homepage', 'weibo_account')


class SubscriptionItem(models.Model):
    """SubscriptionItem table info - email notification."""
    user = models.ManyToManyField(User)
    key = models.CharField(max_length=255)
    item = models.CharField(max_length=255)


class SubscriptionItemAdmin(admin.ModelAdmin):
    """The set of SubscriptionItem table displaying in admin page."""
    list_display = ('key', 'item')


class SecurityVerification(models.Model):
    """SecurityVerification table info."""
    VERIFICATION_TYPE = (
        (1, 'email'),
        (2, 'phone'),
    )
    user = models.ForeignKey(User)
    vtype = models.IntegerField(choices=VERIFICATION_TYPE)
    value = models.CharField(max_length=255)
    is_verified = models.BooleanField(default=False)
    verified_date = models.DateTimeField(auto_now=True)


class UserLoginInfo(models.Model):
    """User login info."""
    user = models.ForeignKey(User)
    ip = models.CharField(max_length=255, null=True)
    #The address that IP belong.
    address = models.CharField(max_length=255, null=True)
    login_date = models.DateTimeField(auto_now_add=True)


class BlackList(models.Model):
    """Black list."""
    user = models.ForeignKey(User)
    comment = models.CharField(max_length=255, null=True)
    create_time = models.DateTimeField(auto_now_add=True)


class BlackListAdmin(admin.ModelAdmin):
    """The set of SubscriptionItem table displaying in admin page."""
    list_display = ('user', 'comment', 'create_time')


admin.site.register(UserPrivateItem, UserPrivateItemAdmin)
admin.site.register(UserDetail, UserDetailAdmin)
admin.site.register(SubscriptionItem, SubscriptionItemAdmin)
admin.site.register(UserPublicProfile, UserPublicProfileAdmin)
admin.site.register(BlackList, BlackListAdmin)
admin.site.register(UserPrivateSetting)
admin.site.register(SecurityVerification)
admin.site.register(UserLoginInfo)

usersetting/forms.py
__author__ = 'rulongwang'

from django.utils.translation import ugettext as _
from django import forms
from usersetting import models
from django.contrib.auth.models import User


class RegisterForm(forms.Form):
    email = forms.EmailField(
        max_length=30,
        # widget=forms.TextInput(attrs={'size': 30,'class': "logon_input",'placeholder': _("Email")}),
        localize=True
    )
    password = forms.CharField(
        max_length=30,
        # widget=forms.PasswordInput(attrs={'size': 20, 'class': "logon_input", 'placeholder': _("Password"),'title':_("At least 6 characters")}),
        # help_text=_('The password length must be more than 6.'),
        localize=True
    )
    username = forms.CharField(
        max_length=30,
        # widget=forms.TextInput(attrs={'size': 20, 'class': "logon_input",'placeholder': _("Username"),'title':_("Only allows Number,Letter,_")}),
        localize=True
    )

    def clean_username(self):
        users = User.objects.filter(username__iexact=self.cleaned_data["username"])
        if not users:
            return self.cleaned_data["username"]
        error_msg = _('%(param)s has been used.') % {'param': self.cleaned_data["username"]}
        raise forms.ValidationError(error_msg)

    def clean_email(self):
        emails = User.objects.filter(email__iexact=self.cleaned_data["email"])
        if not emails:
            return self.cleaned_data["email"]
        error_msg = _('%(param)s has been used.') % {'param': self.cleaned_data["email"]}
        raise forms.ValidationError(error_msg)


class UserDetailForm(forms.ModelForm):
    class Meta:
        model = models.UserDetail

    def __init__(self, *args, **kwargs):
        super(UserDetailForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['user'].widget.attrs['hidden'] = True


class UserPublicProfileForm(forms.ModelForm):
    class Meta:
        model = models.UserPublicProfile

    def __init__(self, *args, **kwargs):
        super(UserPublicProfileForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['user'].widget.attrs['hidden'] = True

templates/usersetting/account_setting.html
{% extends "index.html" %}
{% block mainContent %}
{% load i18n %}
{% load staticfiles %}
    <script>
  $(function() {
    $( "#id_birthday" ).datepicker({
        showOtherMonths: true,
        selectOtherMonths: true,
        changeMonth: true,
        changeYear: true,
        dateFormat: 'yy-mm-dd'
    });

  });
  </script>

       <div id="account_wrapper">
        <div class="pannel_nav">
            <div class="account_nav_title setting_icon">{% trans 'Personal Setting' %}</div>
            <ul class="account_nav">

                <li ><a href="{% url 'usersetting:user_detail' %}">{% trans 'Account Details' %}</a></li>
                <li><a href="{% url 'usersetting:public_profile' %}">{% trans 'Public Profile' %}</a></li>
                <li><a href="{% url 'usersetting:subscription_setting' %}">{% trans 'Subscription Setting' %}</a></li>
                <li><a href="{% url 'usersetting:security_setting' %}">{% trans 'Security Settings' %}</a></li>
            </ul>

            <div class="account_nav_title payment_icon">{% trans 'Account Setting' %}</div>
            <ul class="account_nav">
                <li><a href="{% url 'usersetting:payment_setting' '' %}">{% trans 'Your Account' %}</a></li>
            </ul>
        </div>

        <div class="account_details">
               {% block account_detail %}
                   <div id="account_msg" style="color: green">
                        {{ account_msg }}
                   </div>
                   <div id="account_error" style="color: red">
                        {{ account_msg }}
                   </div>
                   <div class="dash_title">Account Details</div>
                    <form action=""  method="post">
                    {% csrf_token %}
                            <ul class="account_detail_items">
                                    <li>
                                    <div class="fieldWrapper">
                                        <div class="field_label" >{{ form.user.label_tag }}</div>
                                        <div class="field_value" >
                                            <input id="username" name="username" value="{{ request.user.username }}" readonly="true"/>
                                        </div>
                                    </div>
                                    </li>
                                    <li>
                                    <div class="fieldWrapper">
                                        {{ form.birthday.errors }}
                                        <div class="field_label" >{{ form.birthday.label_tag }}</div><div class="field_value" > {{ form.birthday }}</div>
                                    </div>
                                    </li>
                                    <li>
                                    <div class="fieldWrapper">
                                        {{ form.real_name.errors }}
                                        <div class="field_label" >{{ form.real_name.label_tag }}</div><div class="field_value" > {{ form.real_name }}</div>
                                    </div>
                                    </li>
                                    <li>
                                    <div class="fieldWrapper">
                                        {{ form.street_address.errors }}
                                        <div class="field_label" >{{ form.street_address.label_tag }}</div><div class="field_value" > {{ form.street_address }}</div>
                                    </div>
                                    </li>
                                    <li>
                                    <div class="fieldWrapper">
                                        {{ form.city.errors }}
                                        <div class="field_label" >{{ form.city.label_tag }}</div><div class="field_value" > {{ form.city }}</div>
                                    </div>
                                    </li>
                                    <li>
                                    <div class="fieldWrapper">
                                        {{ form.state_provience.errors }}
                                        <div class="field_label" >{{ form.state_provience.label_tag }}</div><div class="field_value" > {{ form.state_provience }}</div>
                                    </div>
                                    </li>
                                    <li>
                                    <div class="fieldWrapper">
                                        {{ form.post_code.errors }}
                                        <div class="field_label" >{{ form.post_code.label_tag }}</div><div class="field_value" > {{ form.post_code }}</div>
                                    </div>
                                    </li>
                                    <li>
                                    <div class="fieldWrapper">
                                        {{ form.country.errors }}
                                        <div class="field_label" >{{ form.country.label_tag }}</div><div class="field_value" > {{ form.country }}</div>
                                    </div>
                                    </li>
                                    <li>

                                </ul>
                                 <div><input id="submit" type="submit" value="Submit"  class="newbutton"/></div>
                    </form>
               {% endblock %}
        </div>
       </div>
<script type="text/javascript" language="javascript">
    $("#submit").click(function() {
        if ($("#id_birthday").val().trim() != "" && !validDate($("#id_birthday").val())) {
            $("#account_error").html("The birthday is not correct.");
            return false;
        }
        if ($("#id_real_name").val().trim() != "" && $("#id_real_name").val().trim().length > 25) {
            $("#account_error").html("The length of real name can not more than 25.");
            return false;
        }
        var tel = /^[0-9]{6}$/;
        if ($("#id_post_code").val().trim() != "" && !tel.test($("#id_post_code").val().trim())) {
            $("#account_error").html("Post code is not correct.");
            return false;
        }
    });
</script>
{% endblock %}

templates/usersetting/forget_password.html
{% extends "usersetting/log_tp.html" %}
{% block logon %}
{% load staticfiles %}
    {% if msg %}
        <div class="message_back">
        {{ msg }}
        </div>
    {% else %}
        <div class="errors_block">
            {{ error_msg }}
        </div>
        <div id="central_block">
            <div class="central_section">
               <form action="" method='post' class="pull-right">
                {% csrf_token %}
                <table class="user_register">
                 <tr>
                     <td>Username/Email</td>
                     <td><input id="id_username" name="username" class="logon_input" /></td>
                 </tr>
                 <tr>
                     <td></td>
                     <td><button id="submit" class="newbutton" type="submit">submit</button></td>
                 </tr>
                </table>
              </form>
            </div>
        </div>
    {% endif %}
<script type="text/javascript" language="javascript">
    $("#submit").click(function() {
        var username = $("#id_username").val().trim();
        if (username == "") {
            $(".errors_block").html("Username/Email is required.");
            return false;
        }
        if (username.indexOf("@") != -1 && !valid_email(username)) {
            $(".errors_block").html("Email is not correct.");
            return false;
        }
    });
</script>
{% endblock %}

templates/usersetting/log_tp.html
{% include 'header.html' %}
<body>

<section id="main">
<div id="logon">
{% block logon %}



{% endblock %}
</div>
</section>


{% include 'footer.html' %}

templates/usersetting/login.html
{% extends "usersetting/log_tp.html" %}
{% block logon %}
{% load i18n %}
{% load staticfiles %}
    <div class="errors_block">
        {% if login_error %}

                    {{ login_error }}
        {% endif %}
    </div>
    <div id="central_block">
        <div class="central_section">
           <form action="/usersetting/login/" method='post' class="pull-right">
            {% csrf_token %}


               <table class="user_register">
                   <tr>
                       <td>
{#                           Username:#}
                       </td>
                       <td>
                           <input id='username' name='username' class="logon_input" type="text" placeholder="{% trans 'User Name' %}" value="{{ user_name }}">
                       </td>
                       <td style="width:200px;">
                             <a href="{% url 'usersetting:register_view' %}">{% trans 'Not register' %}？</a>
                       </td>
                   </tr>
                   <tr>
                       <td>
{#                           Password:#}
                       </td>
                       <td >
                           <input id='password' name='password' class="logon_input" type="password" placeholder="{% trans 'Password' %}">
                       </td>
                       <td>
                            <a href="{% url 'usersetting:forget_password' %}">{% trans 'Forget Password' %}</a>
                       </td>

                   </tr>
                   <tr>
                       <td>
                            <input name="next" value="{{ redirect_to }}" type="hidden">

                       </td>
                       <td style="text-align: center;">
                           <button id="submit" class="newbutton" type="submit">{% trans 'Logon' %}</button>
                       </td>
                       <td>
{#                            <a href="#">Send active email</a>#}
                       </td>

                   </tr>

               </table>




          </form>
        </div>
    </div>
<script type="text/javascript" language="javascript">
    $("#submit").click(function() {
        if ($("#username").val().trim() == "") {
            $(".errors_block").html("Username is required.");
            return false;
        }
        if ($("#password").val().trim() == "") {
            $(".errors_block").html("Password is required.");
            return false;
        }
    });
</script>
{% endblock %}

templates/usersetting/register_active.html
{% extends "index.html" %}
{% block mainContent %}
{% load staticfiles %}
    <div class="message_back">
        <p>Welcome to Appswalk. The activation email has been sent to your email address <span style="color:#ca0100;">{{ email }}</span>.
       </p><p> Please kindly check your email inbox and active your APPSWALK account by clicking the attached activation link.</p>
    </div>
{% endblock %}

templates/usersetting/register_active_confirm.html
{% extends "index.html" %}
{% block mainContent %}
{% load staticfiles %}
    {% if account_msg %}
    <div class="message_back">
        {{ account_msg }} Enjoy your journey at <a href="{% url 'usersetting:home' %}" style="color:#00b0b0;">AppsWalk</a>
    </div>
    {% else %}
    <div class="message_back">
        Active account failed. {{ account_error }}
    </div>
    {% endif %}
{% endblock %}

templates/usersetting/security_setting.html
{% extends "usersetting/account_setting.html" %}
{% block account_detail %}
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
            </li>
        {% endfor %}
        </ul>
    {% endif %}
    {% load staticfiles %}
    <div class="setting_block">
        <div class="dash_title">Security Settings</div>
        <div class="setting_item">
            <div class="setting_item_left correct_icon">Account Password <a id="password_update" class="setting_item_right" href="{% url 'usersetting:security_verification_password' %}"><img src="{% static "images/edit20x20.png" %}"/></a></div>
            <div class="help_text">
                Please keep your account security.
            </div>


        </div>
        <div class="setting_item">
            <div class="setting_item_left
             {% if email_info and email_info.is_verified == True %}
             correct_icon
             {% else %}
             incorrect_icon
             {% endif %}
            ">Email Verification <a id="email_update" class="setting_item_right" href="{% url 'usersetting:security_verification_email' %}">
                <img src="{% static "images/edit20x20.png" %}"/>
            </a>
            </div>
            <div >
                {% if email_info and email_info.is_verified == True %}
                <div class="help_text">Your email: {{ email_info.value }}</div>
                {% elif email_info and email_info.is_verified == False %}
                <div class="help_text">Your email {{ email_info.value }} is not verified. Please active it ASAP. </div>
                {% else %}
                <div class="help_text">
                    Your still have no email. Please provide and verify it ASAP.
                 </div>
                {% endif %}
            </div>


        </div>
{#        <div class="setting_item">#}
{#            <div class="setting_item_left#}
{#             {% if phone_info and phone_info.is_verified == True%}#}
{#             correct_icon#}
{#             {% else %}#}
{#             incorrect_icon#}
{#             {% endif %}#}
{#            ">Cell Verification <a id="phone_update" class="setting_item_right" href="{% url 'usersetting:security_verification_phone' %}"><img src="{% static "images/edit20x20.png" %}"/></a></div>#}
{#            <div>#}
{#                {% if phone_info %}#}
{#                <div class="help_text">Your phone: {{ phone_info.value }}</div>#}
{#                {% else %}#}
{#                <div class="help_text">Your still have no phone. Please provide and verify it ASAP.</div>#}
{#                {% endif %}#}
{#            </div>#}
{#        </div>#}
    </div>

{% endblock %}

templates/usersetting/security_setting_email.html
{% extends "usersetting/account_setting.html" %}
{% block account_detail %}
    <div id="account_error" style="color: red">
        {{ account_error }}
    </div>
    <div id="account_msg" style="color: green">
        {{ account_msg }}
    </div>
    <div class="dash_title">Email Setting</div>
    <div>
    <form action=""  method="post">
        {% csrf_token %}
        <div style="padding:10px;color:#00b0b0;width:300px;float: left;">Please enter the new email:</div>
        <div style="padding:10px;width:300px;float:left;"><input id="id_email" style="padding: 5px;width:280px;border: 1px solid #00b0b0;" name="email"/></div>
        <div><input id="submit" type="submit" value="Update"  class="newbutton"/></div>
    </form>
    </div>
<script type="text/javascript" language="javascript">
    $("#submit").click(function() {
        if ($("#id_email").val().trim() == "") {
            $("#account_error").html("Email is required.");
            return false;
        }
        if (!valid_email($("#id_email").val().trim())) {
            $("#account_error").html("Email is not correct.");
            return false;
        }
    });
</script>
{% endblock %}

templates/usersetting/security_setting_phone.html
{% extends "usersetting/account_setting.html" %}
{% block account_detail %}
    <div id="account_error" style="color: red">
        {{ account_error }}
    </div>
    <div id="account_msg" style="color: green">
        {{ account_msg }}
    </div>
    <div class="dash_title">Cell Phone Verification</div>
    <div>
    <form action=""  method="post">
        {% csrf_token %}
        <div style="padding-top: 20px;">
            Please enter your cell phone number:  <input id="id_phone" style="padding: 5px;width:200px;border: 1px solid #00b0b0;" name="phone"/>
            <input id="id_get_pin" name="get_pin" type="button" value="Get PIN" class="newbutton" />
        </div>
        <div id="pin_msg" style="display: none">
            The PIN has been sent to your cell phone. If you didn't receive it, please get PIN again after <span id="remain_time">60</span>s.
        </div>
        <div style="padding-top: 20px;">
            Please enter PIN code:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;
            <input id="id_pin" style="padding: 5px;width:200px;" name="pin" type="text" disabled />
            <input id="submit" type="submit" value="Submit"  class="newbutton" />
        </div>
    </form>
    </div>
<script type="text/javascript" language="javascript">
    var interval;
    $("#id_get_pin").click(function() {
        $.ajax({
            type:"POST",
            url:"{% url 'usersetting:send_PIN' %}",
            data:{
                csrfmiddlewaretoken: "{{ csrf_token }}"
            },
            success:function(data) {
                if(data.ok === 'true') {
                    $("#id_get_pin").attr("disabled", true);
                    $("#pin_msg").show();
                    $("#id_pin").attr("disabled", false);
                    $("#remain_time").text(60);
                    interval = setInterval("remainTimer()", 1000);
                }
                else {
                    $("#pin_msg").text(data.message);
                    $("#pin_msg").show();
                }
            }
        });
    });

    function remainTimer() {
        remain_second = $("#remain_time").text();
        if (parseInt(remain_second) == 0) {
            clearTimeout(interval);
            $("#id_get_pin").attr("disabled", false);
            $("#id_pin").attr("disabled", true);
            $("#id_pin").val('');
            $("#pin_msg").hide();
            return;
        }
        $("#remain_time").text(parseInt(remain_second) - 1);
    }

    $("#submit").click(function() {
        if ($("#id_phone").val().trim() == "") {
            $("#account_error").html("Phone number is required.");
            return false;
        }
        if (!valid_phone($("#id_phone").val().trim())) {
            $("#account_error").html("Phone number is not correct.");
            return false;
        }
        if ($("#id_pin").val().trim() == "") {
            $("#account_error").html("PIN is required.");
            return false;
        }
        if (isNaN($("#id_pin").val()) || $("#id_pin").val().trim().length != 6) {
            $("#account_error").html("PIN is not correct.");
            return false;
        }
    });
</script>
{% endblock %}