appbid/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^seller/', include('seller.urls', namespace='seller')),
    url(r'^usersetting/', include('usersetting.urls', namespace='usersetting')),
    url(r'^query/', include('query.urls', namespace='query')),
    url(r'^bid/', include('bid.urls', namespace='bid')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^transaction/', include('transaction.urls', namespace='transaction')),
    url(r'^social-auth/', include('social_auth.urls')),
    url(r'^auth/', include('auth.urls', namespace='auth')),
    url(r'^help/', include('help.urls', namespace='help')),
    url(r'^developer/', include('developer.urls', namespace='developer')),
    url(r'^joblistings/', include('offer.urls', namespace='offer')),

    url(r'^', include('favicon.urls')),
)

#urlpatterns += (url(r'^admin/django-ses/', include('django_ses.urls')),)
# urlpatterns += patterns('django.contrib.flatpages.views',
#     url(r'^about-us/$', 'flatpage', {'url': '/about-us/'}, name='about'),
#     url(r'^license/$', 'flatpage', {'url': '/license/'}, name='license'),
# )


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth/urls.py
__author__ = 'Jarvis'

from django.conf.urls import patterns, url
from auth import views

urlpatterns = patterns('',
    url(r'^auth-complete/$', views.authComplete, name='auth_complete'),
    url(r'^auth-error/$', views.authError, name='auth_error'),
)

bid/urls.py
__author__ = 'Jarvis'

from django.conf.urls import patterns, url
from bid import views

urlpatterns = patterns('',
    url(r'^bid-create/(?P<pk>\d+)$', views.createBid, name='bid_create'),
    url(r'^bid-list/(?P<pk>\d+)$', views.bidList, name='bid_list'),
)

dashboard/urls.py
__author__ = 'rulongwang'

from django.conf.urls import patterns, url
from dashboard import views


urlpatterns = patterns('',
    url(r'^inbox$', views.inbox, name='inbox'),
    url(r'^sent-messages$', views.sentMessages, name='sent_messages'),
    url(r'^message-detail/(?P<msg_action>\w+)/(?P<msg_id>\d+)$', views.messageDetail, name='message_detail'),
    url(r'^create-message/(?P<msg_action>\w+)/(?P<type>\d+)/(?P<username>\S+)/(?P<user_id>\d+)/(?P<msg_id>\d*)$',
        views.createMessage, name='create_message'),
    url(r'^download-message/(?P<msg_id>\d+)/(?P<attachment_id>\d+)$', views.downloadAttachment, name='download_message'),

    url(r'^my-listing$', views.myListing, name='my_listing'),
    url(r'^my-bidding$', views.myBidding, name='my_bidding'),

    url(r'^watch-app/(?P<app_id>\d+)$', views.watchApp, name='watch_app'),
    url(r'^unwatch-app/(?P<app_id>\d+)$', views.unwatchApp, name='unwatch_app'),
    url(r'^watch-apps$', views.watchApps, name='watch_apps'),

    url(r'^watch-seller/(?P<user_id>\d+)$', views.watchSeller, name='watch_seller'),
    url(r'^unwatch-seller/(?P<user_id>\d+)$', views.unwatchSeller, name='unwatch_seller'),
    url(r'^watch-sellers$', views.watchSellers, name='watch_sellers'),

    url(r'^watch-category/(?P<category_id>\d+)$', views.watchCategory, name='watch_category'),
    url(r'^unwatch-category/(?P<category_id>\d+)$', views.unwatchCategory, name='unwatch_category'),
    url(r'^watch-categories$', views.watchCategories, name='watch_categories'),

    url(r'^past-transactions$', views.pastTransactions, name='past_transactions'),
    url(r'^past-orders$', views.pasOrders, name='past_orders'),
)

query/urls.py
from django.conf.urls import patterns, url
from query import views

urlpatterns = patterns('',
    url(r'^app-detail/(?P<pk>\d*)$', views.getAppDetail, name='app_detail'),
    url(r'^app-detail-comment/(?P<pk>\d*)$', views.addCommentForApp, name='app_detail_comment'),
    url(r'^bid-info/(?P<pk>\d*)$', views.getBidInfo, name='bid_info'),
    url(r'^featured$', views.listFeatured, name='featured'),
    url(r'^list-latest/$', views.listLatest, name='list_latest'),
    url(r'^most-active/$', views.mostActive, name='most_active'),
    url(r'^ending-soon/$', views.endingSoon, name='ending_soon'),
    url(r'^just-sold/$', views.justSold, name='just_sold'),
    url(r'^list-all/$', views.listAll, name='list_all'),
)

seller/urls.py
from django.conf.urls import patterns, url
from seller import views

urlpatterns = patterns('',
    url(r'^app-store-link/(?P<pk>\d*)$', views.registerApp,
        {'flag': 1.1,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:appStore_info',
         'nextPage2': 'seller:verification',
         'saveMethod': views.saveAppStoreLink,
         }, name='appStore_link'),
    url(r'^app-store-info/(?P<pk>\d+)$', views.registerApp,
        {'flag': 1.2,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:marketing',
         'saveMethod': views.saveAppStoreInfo,
         }, name='appStore_info'),
    url(r'^marketing/(?P<pk>\d+)$', views.registerApp,
        {'flag': 2,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:additional_info',
         'saveMethod': views.saveMarketing,
         }, name='marketing'),
    url(r'^additional-info/(?P<pk>\d+)$', views.registerApp,
        {'flag': 3,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:sale',
         'saveMethod': views.saveAdditionalInfo,
         }, name='additional_info'),
    url(r'^sale/(?P<pk>\d+)$', views.registerApp,
        {'flag': 4,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:delivery',
         'saveMethod': views.saveSale,
         }, name='sale'),
    url(r'^delivery/(?P<pk>\d+)$', views.registerApp,
        {'flag': 5,
         'backPage': 'seller/register_content.html',
         'nextPage': '/seller/payment',
         'saveMethod': views.saveDelivery,
         }, name='delivery'),
    #[a-z] for 'new' key word - create the new payment
    url(r'^payment/(?P<pk>\d+)/(?P<sn>[0-9a-z]*)$', views.registerApp,
        {'flag': 6,
         'backPage': 'seller/register_content.html',
         'nextPage': 'order:checkout',
         'saveMethod': views.saveService,
         }, name='payment'),
    url(r'^verification/(?P<pk>\d+)$', views.registerApp,
        {'flag': 7,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:verification',
         'saveMethod': views.saveVerification,
         }, name='verification'),
    url(r'^delete-attachment/(?P<pk>\d*)$', views.deleteAttachment, name='deleteAttachment'),
    url(r'^become-certified-developer$', views.becomeCertifiedDeveloper, name='become_certified_developer'),
)

transaction/urls.py
__author__ = 'Jarvis'

from django.conf.urls import patterns, url
from transaction import views


urlpatterns = patterns('',
    url(r'^trade-now/(?P<app_id>\d+)/(?P<buyer_id>\d+)/(?P<bid_id>\d+)$', views.tradeNow, name='trade_now'),
    url(r'^trade-action/(?P<action>\w+)/(?P<app_id>\d+)/(?P<user_id>\d+)$', views.tradeAction, name='trade_action'),
    url(r'^closed-trade/(?P<txn_id>\d+)/(?P<buyer_id>\d+)$', views.closedTrade, name='closed_trade'),

    url(r'^one-price-buy/(?P<app_id>\d+)/(?P<publisher_id>\d+)$', views.onePriceBuy, name='one_price_buy'),
    url(r'^buyer-pay/(?P<app_id>\d+)/(?P<txn_id>\d+)/(?P<token>\w{30})$', views.buyerPay, name='buyer_pay'),
    url(r'^remind-buyer/(?P<txn_id>\d*)$', views.remindBuyerPay, name='remind_buyer'),
)

dashboard/models.py
__author__ = 'Jarvis'

from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from appbid import models as appModels


class WatchApp(models.Model):
    """Watch App"""
    app = models.ForeignKey(appModels.App)
    buyer = models.ForeignKey(User)


class WatchCategory(models.Model):
    """Watch Category"""
    category = models.ForeignKey(appModels.Category)
    buyer = models.ForeignKey(User)


class WatchSeller(models.Model):
    """Watch publisher"""
    seller = models.ForeignKey(User, related_name='watch_seller')
    buyer = models.ForeignKey(User, related_name='watch_buyer')

admin.site.register(WatchApp)
admin.site.register(WatchCategory)
admin.site.register(WatchSeller)

templates/dashboard/activity.html
{% extends "index.html" %}
{% block mainContent %}
{% load i18n %}
{% load staticfiles %}
       <div class="clear"></div>
       <div id="account_wrapper">
        <div class="pannel_nav">
        <div class="account_nav_title act_icon">{% trans 'Activity Overview' %}</div>
           <ul class="account_nav">
			<li><a href="{% url 'dashboard:inbox' %}">{% trans 'Inbox' %}</a></li>
			<li class="margin10pxbt"><a href="{% url 'dashboard:sent_messages' %}">{% trans 'Sent Messages' %}</a></li>
          </ul>
        <div class="account_nav_title apps_icon">{% trans 'My Apps' %}</div>
            <ul class="account_nav">
			<li><a href="{% url 'dashboard:my_listing' %}">{% trans 'My Auctions' %}</a></li>
			<li class="margin10pxbt"><a href="{% url 'dashboard:my_bidding' %}">{% trans 'My Bidding' %}</a></li>
          </ul>
        <div class="account_nav_title watch_icon">{% trans 'Watch List' %}</div>
            <ul class="account_nav">
			<li><a href="{% url 'dashboard:watch_apps' %}">{% trans 'Watched Apps' %}</a></li>
			<li><a href="{% url 'dashboard:watch_sellers' %}">{% trans 'Watched Sellers' %}</a></li>
			<li class="margin10pxbt"><a href="{% url 'dashboard:watch_categories' %}">{% trans 'Watched Categories' %}</a></li>
            </ul>
        <div class="account_nav_title people_icon">{% trans 'Your Account' %}</div>
            <ul class="account_nav">
			<li><a href="{% url 'dashboard:past_transactions' %}">{% trans 'Past Transactions' %}</a></li>
			<li><a href="{% url 'dashboard:past_orders' %}">{% trans 'Past Orders' %}</a></li>
          </ul>
        </div>

        <div class="account_details">
               {% block dashboard_detail %}

                   <div class="dash_title">{% trans 'Inbox' %}</div>
                   <ul class="inbox_list">


                       <li class="highlight_li">
                            <div class="inbox_from">{% trans 'From' %}</div>
                            <div class="inbox_subject" >{% trans 'Message Subject' %}</div>
                            <div class="inbox_received_time">{% trans 'Received Time' %}</div>

                        </li>
                       {% for message in message_list %}
                           <li {% ifequal message.0.is_read False %}style="font-weight:bold;" {% endifequal %}>
                           <a href="/dashboard/message-detail/reply/{{ message.0.id }}?page={{ message_list.number }}">
                               <div class="inbox_from" >
                               {{ message.0.sender.username }}

                           </div>
                           <div class="inbox_subject">{{ message.0.title }}</div>
                           <div class="inbox_received_time">{{ message.0.submit_date|date:"Y-m-d H:i"|default:"N/A" }}</div>
                           {% if message.1 %}<img style="width: 20px;" src="{% static "images/msg_attachment.jpg" %}"
                                                  title="{% trans 'The message includes the attachment.' %}" />{% endif %}
                            </a>
                           </li>
                       {% empty %}

                           <div class="no_message">{% trans 'No received message.' %}</div>
                       {% endfor %}
                   </ul>


                     {% if message_list %}
                     <div class="pagination" >
                        {% if message_list.has_previous %}<a href="?page={{ message_list.previous_page_number }}">{% trans 'previous' %}</a>{% endif %}
                        {% trans 'Page' %} {{ message_list.number }} {% trans 'of' %} {{ message_list.paginator.num_pages }}
                        {% if message_list.has_next %}<a href="?page={{ message_list.next_page_number }}">{% trans 'next' %}</a>{% endif %}
                     </div>
                     {% endif %}
               {% endblock %}
        </div>
       </div>
{% endblock %}

templates/dashboard/bidding_management.html
{% extends "dashboard/activity.html" %}
{% block dashboard_detail %}
{#       <fieldset>#}
{#        <legend>My App Bidding</legend>#}
{#           <ul class="inbox_list">#}
{#           <li>#}
{#               <div class="app_title">App title</div>#}
{#               <div class="app_title">Service Begin Time</div>#}
{#               <div class="app_title">Service End Time</div>#}
{#                <div class="app_title">Begin Price</div>#}
{#                <div class="app_title">One Price</div>#}
{#                <div class="app_title">Reserve Price</div>#}
{#                <div class="app_title">Max bid Price</div>#}
{#               <div class="app_title">Bid List</div>#}
{#           </li>#}
{#           {% for app in published_apps %}#}
{#               <li>#}
{#                   <div class="app_title">#}
{#                       <a href="{% url 'query:app_detail' app.0.id %}">{{ app.0.title }}</a>#}
{#                   </div>#}
{#                   <div class="app_title">{{ app.1.0.start_date }}</div>#}
{#                   <div class="app_title"><b>{{ app.1.0.end_date }}</b></div>#}
{#                   <div class="app_title">{{ app.0.begin_price }}{{ app.0.currency.currency }}</div>#}
{#                   <div class="app_title">{{ app.0.one_price }}{{ app.0.currency.currency }}</div>#}
{#                   <div class="app_title">{{ app.0.reserve_price }}{{ app.0.currency.currency }}</div>#}
{#                   <div class="app_title"><b>-100-</b>{{ app.0.currency.currency }}</div>#}
{#                   <div class="app_title">#}
{#                       <a href="{% url 'dashboard:bidding_list' app.0.id %}">Bid List</a>#}
{#                   </div>#}
{#               </li>#}
{#           {% empty %}#}
{#               No app.#}
{#           {% endfor %}#}
{#           {% if published_apps %}#}
{#             <div class="pagination" style="float: right">#}
{#                {% if published_apps.has_previous %}<a href="?bid_page={{ published_apps.previous_page_number }}">previous</a>{% endif %}#}
{#                Page {{ published_apps.number }} of {{ published_apps.paginator.num_pages }}#}
{#                {% if published_apps.has_next %}<a href="?bid_page={{ published_apps.next_page_number }}">next</a>{% endif %}#}
{#             </div>#}
{#           {% endif %}#}
{#           </ul>#}
{#       </fieldset>#}

        <fieldset>
        <legend>My Joined Bidding</legend>
           <ul class="inbox_list">
            <li>
               <div class="app_title">App Name</div>
               <div class="app_title">Bid End Time</div>
               <div class="app_title">My Max Price</div>
               <div class="app_title">Current Price</div>
           </li>
           {% for app in joined_apps %}
               <li>
                   <div class="app_title">
                       <a href="{% url 'query:app_detail' app.0.id %}">{{ app.0.title }}</a>
                   </div>
                   <div class="app_title">{{ app.1.0.start_date }}</div>
                   <div class="app_title">
                       <a href="{% url 'dashboard:bidding_list' app.0.id %}">Bid List</a>
                   </div>
                   <div class="app_title"><a href="{% url 'seller:payment' app.0.id '' %}">RePayment</a></div>
               </li>
           {% empty %}
               No joined bidding.
           {% endfor %}
           {% if joined_apps %}
             <div class="pagination" style="float: right">
                {% if joined_apps.has_previous %}<a href="?joined_page={{ joined_apps.previous_page_number }}">previous</a>{% endif %}
                Page {{ joined_apps.number }} of {{ joined_apps.paginator.num_pages }}
                {% if joined_apps.has_next %}<a href="?joined_page={{ joined_apps.next_page_number }}">next</a>{% endif %}
             </div>
           {% endif %}
           </ul>
       </fieldset>

       <fieldset>
        <legend>My Won Bidding</legend>
           <ul class="inbox_list">
           <li>
               <div class="app_title">App Name</div>
               <div class="app_title">My win Price</div>
               <div class="app_title">Action</div>
               <div class="app_title">Status</div>
           </li>
           {% for app in won_apps %}
               <li>
                   <div class="app_title">
                       <a href="{% url 'query:app_detail' app.0.id %}">{{ app.0.title }}</a>
                   </div>
                   <div class="app_title">{{ app.1.0.start_date }}</div>
                   <div class="app_title">{{ app.1.0.end_date }}</div>
                   <div class="app_title">
                       <a href="{% url 'dashboard:bidding_list' app.0.id %}">Bid List</a>
                   </div>
               </li>
           {% empty %}
               No won bidding.
           {% endfor %}
           {% if won_apps %}
             <div class="pagination" style="float: right">
                {% if won_apps.has_previous %}<a href="?won_page={{ won_apps.previous_page_number }}">previous</a>{% endif %}
                Page {{ won_apps.number }} of {{ won_apps.paginator.num_pages }}
                {% if won_apps.has_next %}<a href="?won_page={{ won_apps.next_page_number }}">next</a>{% endif %}
             </div>
           {% endif %}
           </ul>
       </fieldset>
{% endblock %}

templates/dashboard/my_listing.html
{% extends "dashboard/activity.html" %}
{% load i18n %}
{% load staticfiles %}
{% block dashboard_detail %}
          <div class="dash_title">{% trans 'Draft Apps' %}</div>
          <ul class="inbox_list">
            <li class="highlight_li">
               <div class="app_title" style="width: 140px;;padding-left: 30px;">{% trans 'App Name' %}</div>
               <div class="app_title" style="padding-left:10px;">{% trans 'Last Modify' %}</div>
               <div class="app_title" style="padding-left: 10px;">{% trans 'Is Verified' %}</div>
               <div class="app_title" style="width:120px;">{% trans 'Fees' %}</div>
            </li>
           {% for app in draft_apps %}
               <li>
                   <div class="app_list_edit">
                       <a href="{% url 'seller:appStore_link' app.0.id %}" title="Change" >
                            <img src="{% static "images/edit20x20.png" %}" style="height:15px;width: 15px;"/>
                       </a>
                   </div>
                   <div class="app_list">

                       <a href="{% url 'query:app_detail' app.0.id %}">{{ app.0.app_name|truncatewords:5 }}</a>
                   </div>
                   <div class="app_list">
                       {{ app.0.last_modify|date:"Y-m-d H:i"|default:"N/A" }}
                   </div>
                   {% ifequal app.0.is_verified True %}
                       <div class="app_list">{% trans 'Verified' %}</div>
                       <div class="app_list_shorter"><a href="{% url 'seller:payment' app.0.id '' %}" class="pending_style">{% trans 'Pay It Now' %}</a></div>
                   {% else %}
                       <div class="app_list"><a href="{% url 'seller:verification' app.0.id %}" class="pending_style">{% trans 'Pending' %}</a></div>
                       <div class="app_list_shorter" style="color: #cc3333;">{% trans 'Pending' %}</div>
                   {% endifequal %}
               </li>
           {% empty %}
               <div class="no_message">{% trans 'No draft app.' %}</div>
           {% endfor %}
          </ul>
           {% if draft_apps %}
             <div class="pagination" >
                {% if draft_apps.has_previous %}
                    <a href="?draft_page={{ draft_apps.previous_page_number }}&published_page={{ published_page }}&traded_page={{ traded_page }}">{% trans 'previous' %}</a>
                {% endif %}
                {% trans 'Page' %} {{ draft_apps.number }} {% trans 'of' %} {{ draft_apps.paginator.num_pages }}
                {% if draft_apps.has_next %}
                    <a href="?draft_page={{ draft_apps.next_page_number }}&published_page={{ published_page }}&traded_page={{ traded_page }}">{% trans 'next' %}</a>
                {% endif %}
             </div>
           {% endif %}

          <div class="dash_title">{% trans 'Published Apps' %}</div>
         <ul class="inbox_list">
           <li class="highlight_li">
               <div class="app_title" style="width: 140px;;padding-left: 30px;">{% trans 'App Name' %}</div>
               <div class="app_title" style="padding-left:20px;">{% trans 'Auction Beginning' %}</div>
               <div class="app_title" style="padding-left: 0px;">{% trans 'Auction Ending' %}</div>
               <div class="app_title" style="width:120px;">{% trans 'Bids' %}</div>
           </li>
           {% for app in published_apps %}
                <li>
                   <div class="app_list_edit">
                       <a href="{% url 'seller:appStore_link' app.0.id %}" title="Change" >
                            <img src="{% static "images/edit20x20.png" %}" style="height:15px;width: 15px;"/>
                       </a>
                   </div>
                   <div class="app_list">
                       <a href="{% url 'query:app_detail' app.0.id %}">{{ app.0.app_name|truncatewords:5 }}</a>
                   </div>
                   <div class="app_list">
                       {{ app.0.begin_date|date:"Y-m-d H:i"|default:"N/A" }}
                   </div>
                   <div class="app_list">
                       {{ app.0.end_date|date:"Y-m-d H:i"|default:"N/A" }}
                   </div>
                   <div class="app_list_shorter">
                       <a href="{% url 'bid:bid_list' app.0.id %}">{{ app.1|floatformat|default:0 }} bid{{ app.1|floatformat|pluralize }}</a>
                   </div>
               </li>
           {% empty %}
                <div class="no_message">{% trans 'No published app.' %}</div>
           {% endfor %}
           </ul>
           {% if published_apps %}
             <div class="pagination" >
                {% if published_apps.has_previous %}
                    <a href="?draft_page={{ draft_page }}&published_page={{ published_apps.previous_page_number }}&traded_page={{ traded_page }}">{% trans 'previous' %}</a>
                {% endif %}
                {% trans 'Page' %} {{ published_apps.number }} {% trans 'of' %} {{ published_apps.paginator.num_pages }}
                {% if published_apps.has_next %}
                    <a href="?draft_page={{ draft_page }}&published_page={{ published_apps.next_page_number }}&traded_page={{ traded_page }}">{% trans 'next' %}</a>
                {% endif %}
             </div>
           {% endif %}
          <div class="dash_title">{% trans 'Sold/Closed Apps' %}</div>
           <ul class="inbox_list">
           <li class="highlight_li">
               <div class="app_title">{% trans 'App Name' %}</div>
               <div class="app_title">{% trans 'Sold Price' %}</div>
               <div class="app_title">{% trans 'Action' %}</div>
               <div class="app_title">{% trans 'Status' %}</div>
           </li>
           {% for app in traded_apps %}
               <li>
                   <div class="app_list">
                       <a href="{% url 'query:app_detail' app.0.id %}">{{ app.0.app_name|truncatewords:5 }}</a>
                   </div>
                   <div class="app_list">
                       <a href="{% url 'bid:bid_list' app.0.id %}">{{ app.1.0|default:0 }} {{ app.0.currency.currency }}</a>
                   </div>
                   <div class="app_list">
                       {% if app.1.1 == 1 %}
                           <a href="{% url 'bid:bid_list' app.0.id %}">
                               <input id="id_trade" type="button" value="{% trans 'Trade Now' %}" class="button_n" />
                           </a>
                       {% else %}
                           <a href="{% url 'transaction:trade_action' 'sell' app.0.id request.user.id %}">
                               <input id="id_action" type="button" value="{% trans 'Action' %}" class="button_n" />
                           </a>
                       {% endif %}
                   </div>
                   <div class="app_list">{{ app.1.2 }}</div>
               </li>
           {% empty %}
                           <div class="no_message">{% trans 'No sold/closed app.' %}</div>
           {% endfor %}

           </ul>
    {% if traded_apps %}
             <div class="pagination" >
                {% if traded_apps.has_previous %}
                    <a href="?draft_page={{ draft_page }}&published_page={{ published_page }}&traded_page={{ traded_apps.previous_page_number }}">{% trans 'previous' %}</a>
                {% endif %}
                {% trans 'Page' %} {{ traded_apps.number }} {% trans 'of' %} {{ traded_apps.paginator.num_pages }}
                {% if traded_apps.has_next %}
                    <a href="?draft_page={{ draft_page }}&published_page={{ published_page }}&traded_page={{ traded_apps.next_page_number }}">{% trans 'next' %}</a>
                {% endif %}
             </div>
           {% endif %}
{% endblock %}

templates/dashboard/past_orders.html
{% extends "dashboard/activity.html" %}
{% block dashboard_detail %}
           <div class="dash_title">Post Orders</div>
           <ul class="inbox_list">
            <li class="highlight_li">
               <div class="app_title">App Name</div>
               <div class="app_title">Service Time</div>
               <div class="app_title">Price</div>
               <div class="app_title">Pay Status</div>
           </li>
           {% for serviceDetail in serviceDetails %}
               <li>
                   <div class="app_list">
                       <a href="{% url 'query:app_detail' serviceDetail.0.app.id %}">{{ serviceDetail.0.app.app_name }}</a>
                   </div>
                   <div class="app_list">
                       {{ serviceDetail.0.start_date|date:"Y-m-d H:i" }} - {{ serviceDetail.0.end_date|date:"Y-m-d H:i" }}
                   </div>
                   <div class="app_list">
                       {{ serviceDetail.0.actual_amount|floatformat|default:0 }} {{ serviceDetail.0.app.currency.currency }}
                   </div>
                   <div class="app_list">
                   {% if serviceDetail.0.is_payed %}
                       <a href="{% url 'seller:payment' serviceDetail.0.app.id serviceDetail.0.sn %}">Paid</a>
                   {% else %}
                       <a href="{% url 'seller:payment' serviceDetail.0.app.id serviceDetail.0.sn %}" class="pending_style">UnPaid</a>
                   {% endif %}
                   </div>
               </li>
           {% empty %}
                <div class="no_message">No past orders.</div>
           {% endfor %}
           {% if serviceDetails %}
             <div class="pagination" >
                {% if serviceDetails.has_previous %}<a href="?page={{ serviceDetails.previous_page_number }}">previous</a>{% endif %}
                Page {{ serviceDetails.number }} of {{ serviceDetails.paginator.num_pages }}
                {% if serviceDetails.has_next %}<a href="?page={{ serviceDetails.next_page_number }}">next</a>{% endif %}
             </div>
           {% endif %}
           </ul>
{% endblock %}